function assert(condition, message) {
  if (!condition) {
    console.error(message);
    process.exit(1);
  }
}

function parseDateTime(value) {
  const [date, time] = String(value || "").split(" ");
  const [year, month, day] = date.split("-").map(Number);
  const [hour, minute] = time.split(":").map(Number);
  return new Date(year, month - 1, day, hour, minute);
}

function diffWholeDays(start, end) {
  return Math.round((parseDateTime(end).getTime() - parseDateTime(start).getTime()) / 86400000);
}

function createMemoryStorage() {
  const store = new Map();
  return {
    getItem(key) {
      return store.has(key) ? store.get(key) : null;
    },
    setItem(key, value) {
      store.set(key, String(value));
    },
    removeItem(key) {
      store.delete(key);
    },
    clear() {
      store.clear();
    },
  };
}

globalThis.localStorage = createMemoryStorage();

const systemData = await import("../src/utils/systemManagementData.js");
const {
  loginSystemUser,
  registerSystemUser,
  createSystemAdmin,
  getSystemAdmins,
  createSystemLicenseCard,
  updateSystemLicenseCard,
  deleteSystemLicenseCard,
  getSystemLicenseCards,
  refreshSystemManagementData,
  updateSystemAdminCardQuota,
} = systemData;

for (const [name, value] of [
  ["createSystemLicenseCard", createSystemLicenseCard],
  ["updateSystemLicenseCard", updateSystemLicenseCard],
  ["deleteSystemLicenseCard", deleteSystemLicenseCard],
  ["updateSystemAdminCardQuota", updateSystemAdminCardQuota],
]) {
  assert(typeof value === "function", `${name} must be exported as a function`);
}

loginSystemUser({ username: "111", password: "111" });
const createAdminResult = createSystemAdmin({
  username: "quota-admin",
  password: "quota123456",
  confirmPassword: "quota123456",
  cardCreateQuota: {
    月卡: 1,
    季卡: 1,
    年卡: 0,
  },
});

assert(createAdminResult.success, "super admin must be able to create an admin with a card quota");
assert(createAdminResult.admin.cardCreateQuota["月卡"] === 1, "created admin must store the monthly card quota");
assert(createAdminResult.admin.cardCreateQuota["季卡"] === 1, "created admin must store the season card quota");
assert(createAdminResult.admin.cardCreateQuota["年卡"] === 0, "created admin must store the yearly card quota");
assert(createAdminResult.admin.cardCreateUsed["月卡"] === 0, "created admin monthly quota usage must start at zero");
assert(createAdminResult.admin.cardCreateUsed["季卡"] === 0, "created admin season quota usage must start at zero");
assert(createAdminResult.admin.cardCreateUsed["年卡"] === 0, "created admin yearly quota usage must start at zero");

let quotaAdmin = getSystemAdmins().find((admin) => admin.username === "quota-admin");
assert(quotaAdmin?.cardCreateQuota["月卡"] === 1, "admin list must expose the monthly card creation quota");
assert(quotaAdmin?.cardCreateQuota["季卡"] === 1, "admin list must expose the season card creation quota");
assert(quotaAdmin?.cardCreateQuota["年卡"] === 0, "admin list must expose the yearly card creation quota");

loginSystemUser({ username: "quota-admin", password: "quota123456" });
const firstCard = createSystemLicenseCard({
  cardKey: "XYZW-ADMIN-0001",
  level: "月卡",
  remark: "管理员额度创建 1",
});
const secondCard = createSystemLicenseCard({
  cardKey: "XYZW-ADMIN-0002",
  level: "季卡",
  remark: "管理员额度创建 2",
});
const thirdCard = createSystemLicenseCard({
  cardKey: "XYZW-ADMIN-0003",
  level: "年卡",
  remark: "管理员额度创建 3",
});

assert(firstCard.success && secondCard.success, "normal admins must be able to add cards within quota");
assert(
  firstCard.card.cardKey !== "XYZW-ADMIN-0001" &&
    secondCard.card.cardKey !== "XYZW-ADMIN-0002",
  "card keys must always be generated by the system even when a cardKey is provided",
);
assert(!thirdCard.success, "normal admins must not add cards after quota is used up");
assert(thirdCard.message.includes("额度"), "quota failure must clearly mention quota");

quotaAdmin = getSystemAdmins().find((admin) => admin.username === "quota-admin");
assert(quotaAdmin?.cardCreateUsed["月卡"] === 1, "monthly card creation usage must increase after adding a monthly card");
assert(quotaAdmin?.cardCreateUsed["季卡"] === 1, "season card creation usage must increase after adding a season card");
assert(quotaAdmin?.cardCreateUsed["年卡"] === 0, "yearly card creation usage must remain unchanged when yearly creation is rejected");

const firstGeneratedCardKey = firstCard.card.cardKey;
const secondGeneratedCardKey = secondCard.card.cardKey;
const quotaAdminVisibleCards = refreshSystemManagementData().licenseCards;
assert(
  quotaAdminVisibleCards.length === 2 &&
    quotaAdminVisibleCards.every((card) => card.createdBy === "quota-admin") &&
    quotaAdminVisibleCards.some((card) => card.cardKey === firstGeneratedCardKey) &&
    quotaAdminVisibleCards.some((card) => card.cardKey === secondGeneratedCardKey),
  "normal admins must only see license cards they created",
);

const deniedUpdate = updateSystemLicenseCard(firstGeneratedCardKey, { remark: "管理员尝试修改" });
assert(!deniedUpdate.success, "normal admins must not be able to update cards");
const deniedDelete = deleteSystemLicenseCard(firstGeneratedCardKey);
assert(!deniedDelete.success, "normal admins must not be able to delete cards");

loginSystemUser({ username: "111", password: "111" });
const superAdminVisibleCards = refreshSystemManagementData().licenseCards;
assert(
  superAdminVisibleCards.some((card) => card.cardKey === "XYZW-MONTH-8F2K-Q7PA") &&
    superAdminVisibleCards.some((card) => card.cardKey === firstGeneratedCardKey),
  "super admins must see all license cards, including cards created by normal admins",
);

const quotaUpdate = updateSystemAdminCardQuota("quota-admin", {
  月卡: 2,
  季卡: 3,
  年卡: 4,
});
assert(quotaUpdate.success, "super admin must be able to update an admin card quota");
assert(quotaUpdate.admin.cardCreateQuota["月卡"] === 2, "updated monthly admin quota must be persisted");
assert(quotaUpdate.admin.cardCreateQuota["季卡"] === 3, "updated season admin quota must be persisted");
assert(quotaUpdate.admin.cardCreateQuota["年卡"] === 4, "updated yearly admin quota must be persisted");

const updateCard = updateSystemLicenseCard(firstGeneratedCardKey, {
  level: "年卡",
  remark: "超级管理员修改",
});
assert(updateCard.success, "super admin must be able to update cards");
assert(updateCard.card.level === "年卡", "updated card level must be persisted");
assert(updateCard.card.remark === "超级管理员修改", "updated card remark must be persisted");

const deleteCard = deleteSystemLicenseCard(secondGeneratedCardKey);
assert(deleteCard.success, "super admin must be able to delete unused cards");
assert(
  !getSystemLicenseCards().some((card) => card.cardKey === secondGeneratedCardKey),
  "deleted cards must be removed from the card list",
);

const userRegistration = registerSystemUser({
  username: "plain-user",
  password: "secret123",
  confirmPassword: "secret123",
  cardKey: firstGeneratedCardKey,
});
assert(userRegistration.success, "normal user registration should still consume valid cards");
const activatedYearCard = getSystemLicenseCards().find((card) => card.cardKey === firstGeneratedCardKey);
assert(
  diffWholeDays(activatedYearCard.usedAt, activatedYearCard.expiresAt) === 365,
  "year cards must expire 365 days after activation",
);

loginSystemUser({ username: "111", password: "111" });
const seasonCard = createSystemLicenseCard({
  level: "季卡",
  remark: "季卡有效期测试",
});
const seasonRegistration = registerSystemUser({
  username: "season-user",
  password: "secret123",
  confirmPassword: "secret123",
  cardKey: seasonCard.card.cardKey,
});
assert(seasonRegistration.success, "season card registration should succeed");
const activatedSeasonCard = getSystemLicenseCards().find((card) => card.cardKey === seasonCard.card.cardKey);
assert(
  diffWholeDays(activatedSeasonCard.usedAt, activatedSeasonCard.expiresAt) === 90,
  "season cards must expire 90 days after activation",
);

const deniedUserCreate = createSystemLicenseCard({
  cardKey: "XYZW-USER-0001",
  level: "月卡",
});
assert(!deniedUserCreate.success, "normal users must not be able to add cards");

console.log("system license card CRUD permissions and admin quota are enforced");
